env:
  global:
    - secure: "StAj8h4P9srK9Cvn0ZSlqKt1pVoJ+htUXmJF7MC6UUu3hYOiW8FqM0wgCGTvPZ12Dw96mr9adxP42yDEcntbGeWRybKAw7VKA05uRfMWPvfRQUtwu/cAmIBmSbq6mSqc7MPOpcMdqw0CToPnr0wQXTdRjuHDy3JCJK1uJ9/y8jvhKeu/XyqhNxsHwDZBKDket+aiyUO+jrN6wUbubbfYV56/HSFTxI9meQLoM6e0H+A0MOETdA4W+8ATDbMDjvC22zeq9fFl4G8ysmpjLuTx1Iazsv22GcucM8RbqR+n5yhDb2kT2ifhnWzey+DOYBEmhfMkdP0WFCONmDl2ZtU9E0Slzsjmbc3II9Kq20wK7mrgX5Yh8vf+d2h9GmbkBCaLt7O8AqvF6sATMHEppEH/0O+Wj+vqK5+OuzIgpYJ2vWI6nZqUs5pnNuaegtVH3lXe8nIuHorpJKiCWHmDcWpfgkjf6KZMs3frx5K2mhxK/XhdlfKn+RMnPzl27f5QHc3KF3yfa8DQvlvP9bpPF9xtMTLmaEJzpQGvMBQrapGF5UrhwtZf082mLDCgoGwCcXr7btfFDeT6oY+HPwg1hhYFi+7sfEBpoOdv43JJD6XrljGTaJ4Tb6zo59HWL6kOl9bN0OckNP0fjn//nbCrxs6si4CXiyRCc83xZh/sgbEhTbI="
    - secure: "ZOiUAL4KWbvO4BqDyxUlofVoofJLmVRNfNk3/aIKqVit8FBV8e4QIk8RXtl6LpUZ7Cqs8IVGFmICcrd3XatUOxPwKMlUZ2TeR4u9WjtO/Xtay1J+WVWS4XDKsXEvnElnCN2UZCCSMazX0Mbi35PWxMCkuIFUSdD7ed9HWFlMbfpPcrHjJmfMhRmd7ydw2+eVtcHObzF/F0JtiGiHqS/1JJpON4zbaIKBlfSuD0dzzYb1omUNnboIouUqSBErvfW8ixqmVzzVr+3UsQjqsNjbyDrEQxdFEiFe3V+Kv5BfMGP3ChKCLLcTFtbHxtx07nFfYbFm6/fZsxP2jMwF/sd7yqgmpPn3M3Rfq44LwszWdy4mwAYOM5YmB6RNNDH18pevvVqApqJKWE60fjn1tVU0Oa4wH79S+QfGhv4KSp5yq8NxR1xCPE+z7HQClq0bkXkORqp4ev0MztHchr0Nwvup8Ek7oP2JQ6GRrdrOZ+PokRy/zV64hqofY1aHG42SSSV48zL1jveu0Xvmr953B9CfHLGxfTvEeFmOW1qQLOdBj0M3nlpsdQXJX5c/LzdUajV95JFbAe7eugRbjlf47N7SzPK9zV5EWo52AUbdxlRY/Rq1Qn8IBRClsTHSoX2NntpxKAuuUXk95F5XO8TAVd2Z7j1YSsW/4DaESRjF2/mU4PE="
    - secure: "YMW2uoYpdqtVLWAEq2TcmVStOid//y95sgkRktPI4+AN79kOhjlGGQY0n5LG6DWYSbLycHawpCI+0U3CzEO8zBXrHnX8en0oKMSyedH9C8v41UH3ZRH1xZ+SEe0Y9gqCZT802C60bh0wYCbSLdjAFbfaaNalRv+QT1R44JWuxIZKktM1pzeKun+02eVvY97JmfZWdq2aYfE8UlYzE4rUQdIpbToWrmWydW74atl4y7naZtrJY4Fy9X+Of18cpYC+JhoslG0Q5BuPt5DSdfYspjfExAVHmNh/LyUc8865ZWLUHBdRuLdIv1Z2Xe78a63mUc6w35ZScwHWtzii/WG3aSdaiAdiHq5wn1u+kEY2aHrF102F1uQIccELjjroPEQCJe9Kwif0qW4aOH2LuLB7s1LAFas27VvW7h9An4apWXojwlKXj/72Qw2X8p2vfrqW1IAzzfdvUH9hg2XYkZUNQhZxClnMG6NhGxMEbm1RIDwKXJwg/H528U2lc3ZhK0+XgkaH7MREPfKr3C2aHoYpd8AwpFMvYukjywkO5CJgEwa/p3iUMtubG12dh8PJKC/rPQMOQMfUv9fzrMX/fhAJn/w+0eBLeZ90Wr4Fiu/xKQw9HXUFYTOovP/UTD0SmCmAoBi9/g+zD+4DhStDLD/1fiSfV24G9Oy+sqbApTf1L9k="
    - NODE_ENV: "test"
    - API_NAME: "SERVER-API"
    - HOST: "localhost"
    - PORT: "5000"
    - ENDPOINT: "/api/graphql"
    - ENDPOINT_ERD: "/erd"
    - ENDPOINT_ADMINBRO: "/admin"
    - PASSWORD_ADMINBRO: "admin"
    - USERNAME_ADMINBRO: "admin"
    - SECRET_JWT: "TryAgain"
    - BCRYPT_SALT: 10
    - PASSWORD_LIMIT_CHARACTER: 5
    - TOKEN_EXPIRE_TIME: "1h"
    - LOGS: "FALSE"
    - LOGS_CONSOLE: "FALSE"
    - FROM_EMAIL: "justal.kevin@gmail.com"
    - DB_NAME: "server_api"
    - DB_URI_DATA: "mongodb://localhost:27017/"
    - DB_URI_LOG: "mongodb://localhost:27017/logs"
    - DB_HOST_LOG: "localhost"
    - DB_PORT_LOG: 27017
    - DB_NAME_LOG: "logs"
language: node_js
node_js:
  - 15
services:
  - mongodb
install:
  - npm install nyc -g
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov npm run test
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
